## tinted-jjui (https://github.com/vic/tinted-jjui)
# Scheme name: OneDark Dark
# Scheme author: olimorris (https://github.com/olimorris)
# Template author: Victor Borja <vborja@apache.org> (https://github.com/vic)


"border"   = { fg = "#434852" }
"dimmed"   = { fg = "#434852", bg = "#000000" }
"matched"  = { fg = "#e5c07b" }
"selected" = { bg = "#1c1f24", fg = "#abb2bf", bold = true }
"shortcut" = { fg = "#d55fde" }
"text"     = { fg = "#abb2bf", bg = "#000000" }
"title"    = { fg = "#61afef", bold = true }

"source_marker" = { bg = "#2bbac5", fg = "#000000", bold = true }
"target_marker" = { bg = "#89ca78", fg = "#000000", bold = true }

"status"       = { bg = "#1c1f24" }
"status title" = { fg = "#000000", bg = "#61afef", bold = true }

"revset completion dimmed"   = { fg = "#434852" }
"revset completion matched"  = { fg = "#e5c07b", bold = true }
"revset completion selected" = { bg = "#2c313a", fg = "#abb2bf" }
"revset completion text"     = { fg = "#abb2bf" }
"revset text"                = { fg = "#abb2bf", bold = true }
"revset title"               = { fg = "#61afef", bold = true }

"oplog selected"             = { bold = true }
"revisions"                  = { fg = "#abb2bf" }
"revisions details selected" = { bg = "#2c313a" }
"revisions dimmed"           = { fg = "#434852" }
"revisions selected"         = { bg = "#1c1f24" }

"evolog"          = { fg = "#abb2bf" }
"evolog selected" = { bg = "#2c313a", fg = "#abb2bf", bold = true }

"menu"          = { bg = "#000000" }
"menu border"   = { fg = "#1c1f24" }
"menu dimmed"   = { fg = "#434852" }
"menu matched"  = { fg = "#e5c07b", bold = true }
"menu selected" = { bg = "#2c313a", fg = "#abb2bf" }
"menu shortcut" = { fg = "#d55fde" }
"menu title"    = { fg = "#000000", bg = "#d55fde", bold = true }

"help"        = { bg = "#000000" }
"help border" = { fg = "#1c1f24" }
"help title"  = { fg = "#89ca78", bold = true, underline = true }

"preview"        = { fg = "#abb2bf" }
"preview border" = { fg = "#1c1f24" }

"confirmation"          = { bg = "#000000" }
"confirmation border"   = { fg = "#ef596f", bold = true }
"confirmation dimmed"   = { fg = "#434852" }
"confirmation selected" = { bg = "#2c313a", fg = "#abb2bf" }
"confirmation text"     = { fg = "#61afef", bold = true }

"undo"                       = { bg = "#000000" }
"undo confirmation dimmed"   = { fg = "#434852" }
"undo confirmation selected" = { bg = "#2c313a", fg = "#abb2bf" }

"error"                          = { fg = "#ef596f", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status dimmed"                  = { fg = "#434852" }
"status shortcut"                = { fg = "#d55fde" }
"success"                        = { fg = "#89ca78", bold = true }

"completion"          = { fg = "#abb2bf" }
"completion selected" = { bold = true }
"details"             = { fg = "#abb2bf" }
"details selected"    = { bold = true }
"rebase"              = { bold = true }

"bookmark"  = { fg = "#d55fde" }
"branch"    = { fg = "#d19a66" }
"change"    = { fg = "#ef596f" }
"commit"    = { fg = "#89ca78" }
"file"      = { fg = "#e5c07b" }
"workspace" = { fg = "#61afef" }
