[documents]
  git_stop_words = ""

[secrets]
  cnycode_email_address        = "op://shrt4l7sv353awclwbr5jneyga/vbcl447otne532xfzutrvjyfyq/cnycode_email_address"
  context7_api_key             = "op://lprwq74nsfjujjc2r2upmde2x4/6odrhgkho443rcbhtirq54bza4/credential"
  git_signing_key_cny          = "op://lprwq74nsfjujjc2r2upmde2x4/mldcjwxq57p65cg663sj5rf5hq/public key"
  git_signing_key_phyne        = "op://lprwq74nsfjujjc2r2upmde2x4/ijlr7noyo5dzqlez7pmahmmsh4/public key"
  github_personal_access_token = "op://lprwq74nsfjujjc2r2upmde2x4/vhwa5cuhfxd4dwd25yzrowqhzy/token"
  oco_apikey                   = "op://lprwq74nsfjujjc2r2upmde2x4/uebqgq73uv37uvqouxqd3twhsu/opencommit_apikey"
  oco_apiurl                   = "op://lprwq74nsfjujjc2r2upmde2x4/uebqgq73uv37uvqouxqd3twhsu/opencommit_apiurl"
  opencode_apikey              = "op://lprwq74nsfjujjc2r2upmde2x4/uebqgq73uv37uvqouxqd3twhsu/opencode"
  ref_api_key                  = "op://lprwq74nsfjujjc2r2upmde2x4/cplql5u3vahirokxoy4h4dbscq/credential"
  seraphynee_email             = "op://shrt4l7sv353awclwbr5jneyga/vbcl447otne532xfzutrvjyfyq/seraphynee_email_address"
  wakatime_apikey              = "op://lprwq74nsfjujjc2r2upmde2x4/cgxukmmd3tvejpkf7zeqhvmqby/apikey"
  [secrets.espanso]
    em1     = "op://shrt4l7sv353awclwbr5jneyga/xqouwsuluixgnapphubev3dmye/em1"
    em2     = "op://shrt4l7sv353awclwbr5jneyga/xqouwsuluixgnapphubev3dmye/em2"
    em3     = "op://shrt4l7sv353awclwbr5jneyga/xqouwsuluixgnapphubev3dmye/em3"
    em4     = "op://shrt4l7sv353awclwbr5jneyga/xqouwsuluixgnapphubev3dmye/em4"
    em5     = "op://shrt4l7sv353awclwbr5jneyga/xqouwsuluixgnapphubev3dmye/em5"
    lnxarch = "op://shrt4l7sv353awclwbr5jneyga/s2oax2aunv7hpljvkjdwlnysja/scrtlnx"
    onepw   = "op://shrt4l7sv353awclwbr5jneyga/s2oax2aunv7hpljvkjdwlnysja/secret"
  [secrets.ai_help]
    five  = "op://lprwq74nsfjujjc2r2upmde2x4/72amw74rlk2obuc2r5udcx7muu/five"
    four  = "op://lprwq74nsfjujjc2r2upmde2x4/72amw74rlk2obuc2r5udcx7muu/four"
    one   = "op://lprwq74nsfjujjc2r2upmde2x4/72amw74rlk2obuc2r5udcx7muu/one"
    three = "op://lprwq74nsfjujjc2r2upmde2x4/72amw74rlk2obuc2r5udcx7muu/three"
    two   = "op://lprwq74nsfjujjc2r2upmde2x4/72amw74rlk2obuc2r5udcx7muu/two"
  [secrets.ai_help_2]
    five  = "op://lprwq74nsfjujjc2r2upmde2x4/32jclbuyceysrbwibst3t6wjny/five"
    four  = "op://lprwq74nsfjujjc2r2upmde2x4/32jclbuyceysrbwibst3t6wjny/four"
    three = "op://lprwq74nsfjujjc2r2upmde2x4/32jclbuyceysrbwibst3t6wjny/three"
    two   = "op://lprwq74nsfjujjc2r2upmde2x4/32jclbuyceysrbwibst3t6wjny/two"
