[[session]]
  name = "Downloads ðŸ“¥"
  path = "~/Downloads"
  # startup_command = "ls"

[[session]]
  name            = "tmux Config"
  path            = "~/.local/share/chezmoi/chezmoi/dot_config/tmux"
  preview_command = "bat --color=always ~/.config/tmux/tmux.conf"    # startup_command = "nvim tmux.conf"
  startup_command = "nvim tmux.conf.tmpl"

[[session]]
  name = "obsidian"
  path = "~/Documents/vault-obsidian"

[[session]]
  name            = "dotfiles"
  path            = "~/.local/share/chezmoi"
  startup_command = "nvim"
  windows         = [".config"]

[[window]]
  name           = ".config"
  path           = "~/.config"
  startup_script = "nvim"

[[session]]
  name            = "backend"
  path            = "~/Code/Personal/Projects/Backend/allweezy-backend"
  startup_command = "nvim"
  windows         = ["opencode", "codex", "terminal"]

[[window]]
  name           = "opencode"
  startup_script = "opencode"

[[window]]
  name           = "codex"
  startup_script = "codex"

[[window]]
  name           = "terminal"
  startup_script = "doppler run -- bun run dev"

[[session]]
  name            = "OS"
  path            = "~"
  startup_command = "yazi"
  windows         = ["monitoring"]

[[window]]
  name           = "monitoring"
  startup_script = "btop"
